#!/bin/bash

set -e

cd llvm-project

mkdir build
cd build

cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt;clang-tools-extra" -DLLVM_ENABLE_RUNTIMES="all" -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../llvm
make -j10